version: '3'
services: 
  app:
    container_name: budget-tressa
    command: python run.py run -h 0.0.0.0
    build: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app/
    ports: 
      - 5000:5000
    depends_on: 
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
      
volumes:
    postgres_data:
