version: '3'
services: 
  app:
    container_name: budget-tressa
    command: python run.py run -h 0.0.0.0
    build: .
    volumes:
      - .:/usr/src/app/
    ports: 
      - 5000:5000
    depends_on: 
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=budget_tressa_user
      - POSTGRES_PASSWORD=budget_tressa_password
      - POSTGRES_DB=budget_tressa_dev

volumes:
    postgres_data:
    


